# Generated by Django 6.0.1 on 2026-02-03 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produk', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produk',
            name='harga',
            field=models.IntegerField(),
        ),
    ]
